import type { SalesInsights } from "../lib/api";
export function HistoricalSales({ history }: { history: SalesInsights["history"] }) {
    const orderMetric = history.metric === "ORDERS";
    const recent = history.months.slice(-12);
    const percent = (value: number | null) => value === null ? "More data needed" : `${value > 0 ? "+" : ""}${value}%`;
    const monthName = (value: string) => new Date(`${value}-01T12:00:00Z`).toLocaleDateString(undefined, { month: "short", year: "numeric", timeZone: "UTC" });
    return <div className="historical-sales"><h3>Calendar-month patterns</h3><p className="detail-info">{history.completeMonths} of 24 complete months available. {history.status}</p>
        {!orderMetric && <p className="detail-info">This saved report uses legacy summed quantities, which can mix weights and item counts. Generate a new report for order-based store patterns.</p>}<div className="table-wrapper"><table><caption>Last 12 completed calendar months; year-over-year changes compare daily sales rates.</caption><thead><tr><th>Month</th><th>{orderMetric ? "Orders" : "Legacy units"}</th><th>{orderMetric ? "Orders / day" : "Legacy units / day"}</th><th>Change vs same month last year</th></tr></thead><tbody>{recent.map((month, index) => <tr key={month.month}><td>{monthName(month.month)}</td><td>{(orderMetric ? month.orders : month.units)?.toLocaleString() ?? "Not covered"}</td><td>{(orderMetric ? month.ordersPerDay : month.unitsPerDay) ?? "—"}</td><td>{percent((orderMetric ? history.comparisons[index]?.dailyOrdersChangePercent : history.comparisons[index]?.dailyUnitsChangePercent) ?? null)}</td></tr>)}</tbody></table></div>
        {history.recurringPatterns.length > 0 && <div className="detail-info"><strong>Patterns to investigate</strong><ul>{history.recurringPatterns.map(pattern => <li key={pattern.calendarMonth}>{new Date(Date.UTC(2024, pattern.calendarMonth - 1, 1)).toLocaleDateString(undefined, { month: "long", timeZone: "UTC" })}: {pattern.direction.toLowerCase()} {orderMetric ? "orders" : "legacy units"} per day in both cycles ({pattern.earlierIndex}× and {pattern.latestIndex}× their annual daily averages).</li>)}</ul><p>Investigate promotions, stock availability and store changes before attributing this to seasonality.</p></div>}
        {history.productComparisons.length > 0 && <><h3>Leading products: same month, last year</h3><div className="table-wrapper"><table><thead><tr><th>Product</th><th>{monthName(history.productComparisons[0].month)} units</th><th>{monthName(history.productComparisons[0].previousMonth)} units</th><th>Daily rate change</th></tr></thead><tbody>{history.productComparisons.map(product => <tr key={product.productId}><td>{product.name}<small> · {product.unit ?? "unit not recorded"}</small></td><td>{product.units?.toLocaleString() ?? "Incompatible units"}</td><td>{product.previousUnits?.toLocaleString() ?? "Incompatible units"}</td><td>{percent(product.dailyUnitsChangePercent)}</td></tr>)}</tbody></table></div></>}
        <details className="insight-method"><summary>Comparison method and limitations</summary><p>{history.methodology}</p><p>The first Clover import covers up to 90 days. Longer history accumulates while your store stays connected; reconnecting does not create older history.</p></details>
    </div>;
}
