CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    barcode VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(150) NOT NULL,
    brand VARCHAR(120),
    category VARCHAR(120),
    quantity INTEGER NOT NULL DEFAULT 0,
    reorder_level INTEGER NOT NULL DEFAULT 5,
    target_stock INTEGER NOT NULL DEFAULT 20,
    unit_cost DECIMAL(12, 2),
    clover_item_id VARCHAR(64) UNIQUE,
    source VARCHAR(32) NOT NULL DEFAULT 'MANUAL',
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_products_quantity
        CHECK (quantity >= 0),

    CONSTRAINT chk_products_reorder_level
        CHECK (reorder_level >= 0),

    CONSTRAINT chk_products_target_stock
        CHECK (target_stock >= reorder_level),

    CONSTRAINT chk_products_unit_cost
        CHECK (unit_cost IS NULL OR unit_cost >= 0)
);