CREATE TABLE account_email_request_guard (id INTEGER PRIMARY KEY);
INSERT INTO account_email_request_guard(id) VALUES (1);
CREATE TABLE account_email_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email_hash VARCHAR(64) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_account_email_request_time ON account_email_requests(created_at);
CREATE INDEX ix_account_email_request_address ON account_email_requests(email_hash, created_at);
CREATE INDEX ix_account_email_job_created ON account_email_jobs(created_at);
