CREATE TABLE inventory_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    movement_type VARCHAR(32) NOT NULL,
    quantity_change INTEGER NOT NULL,
    quantity_before INTEGER NOT NULL,
    quantity_after INTEGER NOT NULL,
    source VARCHAR(32) NOT NULL DEFAULT 'MANUAL',
    note VARCHAR(255),
    external_reference VARCHAR(128),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_inventory_movement_product
        FOREIGN KEY (product_id)
        REFERENCES products(id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_inventory_movement_type
        CHECK (movement_type IN ('SALE', 'RESTOCK', 'ADJUSTMENT')),

    CONSTRAINT chk_inventory_movement_source
        CHECK (source IN ('MANUAL', 'CLOVER', 'SYSTEM')),

    CONSTRAINT chk_inventory_movement_change
        CHECK (quantity_change <> 0),

    CONSTRAINT chk_inventory_movement_before
        CHECK (quantity_before >= 0),

    CONSTRAINT chk_inventory_movement_after
        CHECK (quantity_after >= 0),

    CONSTRAINT chk_inventory_movement_balance
        CHECK (quantity_after = quantity_before + quantity_change),

    CONSTRAINT chk_inventory_movement_direction
        CHECK (
            (movement_type = 'SALE' AND quantity_change < 0)
            OR
            (movement_type = 'RESTOCK' AND quantity_change > 0)
            OR
            (movement_type = 'ADJUSTMENT')
        ),

    CONSTRAINT uq_inventory_movement_external_reference
        UNIQUE (source, external_reference)
);

CREATE INDEX idx_inventory_movements_product_created
    ON inventory_movements(product_id, created_at);