CREATE TABLE organizations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    slug VARCHAR(100) NOT NULL UNIQUE,
    subscription_plan VARCHAR(32) NOT NULL DEFAULT 'FREE',
    subscription_status VARCHAR(32) NOT NULL DEFAULT 'TRIALING',
    stripe_customer_id VARCHAR(255) UNIQUE,
    trial_ends_at TIMESTAMP WITH TIME ZONE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_organization_subscription_plan
        CHECK (
            subscription_plan IN (
                'FREE',
                'STARTER',
                'PROFESSIONAL',
                'ENTERPRISE'
            )
        ),

    CONSTRAINT chk_organization_subscription_status
        CHECK (
            subscription_status IN (
                'TRIALING',
                'ACTIVE',
                'PAST_DUE',
                'CANCELED'
            )
        )
);

CREATE TABLE stores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    name VARCHAR(150) NOT NULL,
    slug VARCHAR(100) NOT NULL,
    address_line_1 VARCHAR(150),
    address_line_2 VARCHAR(150),
    city VARCHAR(100),
    state VARCHAR(100),
    postal_code VARCHAR(20),
    country_code VARCHAR(2) NOT NULL DEFAULT 'US',
    timezone VARCHAR(64) NOT NULL DEFAULT 'America/New_York',
    currency_code VARCHAR(3) NOT NULL DEFAULT 'USD',
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_store_organization
        FOREIGN KEY (organization_id)
        REFERENCES organizations(id)
        ON DELETE RESTRICT,

    CONSTRAINT uq_store_organization_slug
        UNIQUE (organization_id, slug),

    CONSTRAINT chk_store_country_code_length
        CHECK (CHAR_LENGTH(country_code) = 2),

    CONSTRAINT chk_store_currency_code_length
        CHECK (CHAR_LENGTH(currency_code) = 3)
);

CREATE TABLE app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    first_name VARCHAR(80) NOT NULL,
    last_name VARCHAR(80) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    last_login_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE organization_memberships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    role VARCHAR(32) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_membership_organization
        FOREIGN KEY (organization_id)
        REFERENCES organizations(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_membership_user
        FOREIGN KEY (user_id)
        REFERENCES app_users(id)
        ON DELETE RESTRICT,

    CONSTRAINT uq_membership_organization_user
        UNIQUE (organization_id, user_id),

    CONSTRAINT chk_membership_role
        CHECK (
            role IN (
                'OWNER',
                'ADMIN',
                'MANAGER',
                'EMPLOYEE'
            )
        )
);

CREATE INDEX idx_stores_organization
    ON stores(organization_id);

CREATE INDEX idx_memberships_user
    ON organization_memberships(user_id);

CREATE INDEX idx_memberships_organization
    ON organization_memberships(organization_id);

CREATE INDEX idx_users_enabled_email
    ON app_users(enabled, email);

INSERT INTO organizations (
    name,
    slug,
    subscription_plan,
    subscription_status,
    active
)
VALUES (
    'Splynt Demo Organization',
    'splynt-demo',
    'FREE',
    'ACTIVE',
    TRUE
);

INSERT INTO stores (
    organization_id,
    name,
    slug,
    timezone,
    currency_code,
    active
)
SELECT
    id,
    'Demo Store',
    'demo-store',
    'America/New_York',
    'USD',
    TRUE
FROM organizations
WHERE slug = 'splynt-demo';